microsoft/git

- t/t7524-serialized-status.sh
- wt-status-deserialize.c
- wt-status-serialize.c
- wt-status.h
Update the status serialization cache to contain the new rename_status field.
This allows "git status --deserialize" to correctly report renames.
Also include minor commit to update comments around the ahead_behind_flags
in the status cache header record.
> GVFS serialize status updates

- wt-status-deserialize.c
- wt-status-serialize.c
- wt-status.h
Changes to the global or repo-local excludes files can change the
results returned by "git status" for untracked files.  Therefore,
it is important that the exclude-file values used during serialization
are still current at the time of deserialization.
Teach "git status --serialize" to report metadata on the user's global
exclude file (which defaults to "$XDG_HOME/git/ignore") and for the
repo-local excludes file (which is in ".git/info/excludes").  Serialize
will record the pathnames and mtimes for these files in the serialization
header (next to the mtime data for the .git/index file).
Teach "git status --deserialize" to validate this new metadata.  If either
exclude file has changed since the serialization-cache-file was written,
then deserialize will reject the cache file and force a …
> serialize-status: serialize global and repo-local exclude file metadata

- Documentation/config.txt
- builtin/commit.c
- t/t7524-serialized-status.sh
- wt-status-deserialize.c
- wt-status.h
Extend `git status --deserialize` to better handle stale status cache files.
Add new `--deserialize-wait` command line argument and `status.deserializeWait` config setting.
> status: deserialization wait

- merge-recursive.c
- t/t3507-cherry-pick-conflict.sh
Changes in 2.18.0 induced a bug in merge_content() when merging files that are not present in the local working directory due to sparse-checkout. Fast track the bug fix into our fork as GVFS requires correct behavior with sparse-checkout.
> Fast track bug fix to merge-recursive

- config.c
Closes #13
Some git commands spawn helpers and redirect the index to a different
location.  These include "difftool -d" and the sequencer
(i.e. `git rebase -i`, `git cherry-pick` and `git revert`) and others.
In those instances we don't want to update their temporary index with
our virtualization data.
Helped-by: Johannes Schindelin <johannes.schindelin@gmx.de>
Signed-off-by: Ben Peart <Ben.Peart@microsoft.com>
> virtualfilesystem: don't run the virtual file system hook if the index has been redirected

- cache-tree.c
- cache-tree.h
- diff-lib.c
- dir.c
- name-hash.c
- preload-index.c
- read-cache.c
- t/README
- t/test-lib.sh
- trace.c
- trace.h
- unpack-trees.c
Fast track optimization to unpack-trees() that utilizes the cache tree to avoid traversing parts of the tree that are the same between the two commits.
> Unpack trees with cache tree gvfs

- virtualfilesystem.c
The virtual file system code incorrectly treated symlinks as directories
instead of regular files.  This meant symlinks were not included even if
they are listed in the list of files returned by the core.virtualFilesystem
hook proc.  Fixes #25
Signed-off-by: Ben Peart <Ben.Peart@microsoft.com>
> virtualfilesystem: fix bug with symlinks being ignored

- read-cache.c
On file systems that support it, this can dramatically speed up operations
like add, commit, describe, rebase, reset, rm that would otherwise have to
lstat() every file to "re-match" the stat information in the index to that
of the file system.
On a synthetic repo with 1M files, "git reset" dropped from 52.02 seconds to
14.42 seconds for a savings of 72%.
Signed-off-by: Ben Peart <Ben.Peart@microsoft.com>
> Enable the filesystem cache (fscache) in refresh_index().

- compat/poll/poll.c
Windows Vista (and later) actually have a working poll(), but we still
cannot use it because it only works on sockets.
So let's detect when we are targeting Windows Vista and undefine those
constants, and define `pollfd` so that we can declare our own pollfd
struct.
We also need to make sure that we override those constants *after*
`winsock2.h` has been `#include`d (otherwise we would not really
override those constants).
(Stolen from @jeffhostetler's PR, thanks to @dscho)
> compat/poll: prepare for targeting Windows Vista

- Documentation/config.txt
- read-cache.c
- t/perf/p0002-read-cache.sh
Reverts a stale GVFS specific perf test and removes the GVFS specific optimization to avoid computing the SHA1-1 on index load which is no longer needed.
> Revert "gvfs: add a perf test for reading the index"

- t/t1092-virtualfilesystem.sh
- virtualfilesystem.c
Add check to see if a directory is included in the virtualfilesystem
before checking the directory hashmap.  This allows a directory entry
like foo/ to find all untracked files in subdirectories.
> virtualfilesystem: check if directory is included

- builtin/rebase.c
- builtin/stash.c
William Baker reported that the non-built-in rebase and stash fail to
run the post-command hook (which is important for VFS for Git, though).
The reason is that an `exec()` will replace the current process by the
newly-exec'ed one (our Windows-specific emulation cannot do that, and
does not even try, so this is only an issue on Linux/macOS). As a
consequence, not even the atexit() handlers are run, including the
one running the post-command hook.
To work around that, let's spawn the legacy rebase/stash and exit with
the reported exit code.
> Avoid `sane_execvp` in `git rebase` and `git stash`

- builtin/pack-objects.c
During a 'git push' command, we run 'git send-pack' inside of our
transport helper. This creates a 'git pack-objects' process and
passes a list of object ids. If this list is large, then the
pack-objects process can spend a lot of time checking the possible
refs these strings could represent.
Remove this extra check by setting core.warnAmbiguousRefs to false
as we call 'git pack-objects'.
I was able to see the thousands of calls to different refs using a PerfView trace with "File I/O" selected. After this change, seconds of reading thousands of files was removed.
> pack-objects: ignore ambiguous object warnings

- Documentation/git-apply.txt
- Documentation/git-cvsserver.txt
- Documentation/git-diff-index.txt
- Documentation/git-merge.txt
- Documentation/git-rerere.txt
- Documentation/git-rm.txt
- Documentation/git-svn.txt
- Documentation/git-update-index.txt
- Documentation/gitcore-tutorial.txt
- Documentation/gitrepository-layout.txt
- Documentation/gittutorial.txt
- Documentation/merge-options.txt
- Documentation/technical/pack-protocol.txt
- Documentation/technical/trivial-merge.txt
- Documentation/user-manual.txt
- builtin/merge.c
- contrib/subtree/t/t7900-subtree.sh
- git-gui/po/README
- git-merge-octopus.sh
- git-p4.py
- merge-recursive.c
- notes-merge.c
- remote.c
- t/t6040-tracking-info.sh
- t/t6044-merge-unrelated-index-changes.sh
- templates/hooks--pre-rebase.sample
- unpack-trees.c
@mjcheetham reported in https://github.com/Microsoft/git/pull/71/files/6657af1814168738a04aadb31ce2badcbf0e669f#r235352371 that we no longer need to revert this upstream commit. So let's drop it.
> Stop reverting the "up-to-date"->"up to date" patch

- t/t1092-virtualfilesystem.sh
- virtualfilesystem.c
The vfs does not correctly handle the case when there is a file
that begins with the same prefix as a directory. For example, the
following setup would encounter this issue:
A directory contains a file named `dir1.sln` and a directory
named `dir1/`.
The directory `dir1` contains other files.
The directory `dir1` is in the virtual file system list
The contents of `dir1` should be in the virtual file system, but
it is not. The contents of this directory do not have the skip
worktree bit cleared as expected. The problem is in the
`apply_virtualfilesystem(…)` function where it does not include
the trailing slash of the directory name when looking up the
position in the index to start clearing the skip worktree bit.
This fix is it include the trailing slash when finding the first
index entry …
> virtualfilesystem: fix case where directories not handled correctly

- builtin/update-index.c
- git.c
- gvfs.h
- t/t0402-block-command-on-gvfs.sh
The following commands and options are not currently supported when working
in a GVFS repo.  Add code to detect and block these commands from executing.
1) fsck
2) gc
4) prune
5) repack
6) submodule
8) update-index --split-index
9) update-index --index-version (other than 4)
10) update-index --[no-]skip-worktree
11) worktree
Signed-off-by: Ben Peart <benpeart@microsoft.com>
> gvfs: block unsupported commands when running in a GVFS repo

- .gitattributes
- t/.gitattributes
The new test_oid machinery in the test library requires reading
some information from t/hash-info/hash-info and t/hash-info/oid.
The shell logic that reads from these files is sensitive to CRLF
line endings, causing a problem when the test suite is run on a
Windows machine that converts LF to CRLF.
Exclude the files in this folder from this conversion.
> .gitattributes: ensure t/oid-info/* has eol=lf

- builtin/rebase.c
Builtin rebase had a performance regression compared to the scripted version. It boils down to an extra index read/write at the end of the command.
> Builtin rebase perf fix

- Documentation/config/pack.txt
- Documentation/git-pack-objects.txt
- bisect.c
- builtin/pack-objects.c
- builtin/rev-list.c
- http-push.c
- list-objects.c
- list-objects.h
- revision.c
- revision.h
- t/README
- t/t5322-pack-objects-sparse.sh
One of the biggest remaining pain points for users of very large repositories is the time it takes to run 'git push'. We inspected some slow pushes by our developers and found that the "Enumerating Objects" phase of a push was very slow. This is unsurprising, because this is why reachability bitmaps exist. However, reachability bitmaps are not available to us because of the single pack-file requirement. The bitmap approach is intended for servers anyway, and clients have a much different behavior pattern.
Specifically, clients are normally pushing a very small number of objects compared to the entire working directory. A typical user changes only a small cone of the working directory, so let's use that to our benefit.
Create a new "sparse" mode for 'git pack-objects' that uses the paths …
> A new sparse algorithm for walking trees in push 

- commit-graph.c
When writing a commit-graph, we write GRAPH_MISSING_PARENT if the
parent's object id does not appear in the list of commits to be
written into the commit-graph. This was done as the initial design
allowed commits to have missing parents, but the final version
requires the commit-graph to be closed under reachability. Thus,
this GRAPH_MISSING_PARENT value should never be written.
However, there are reasons why it could be written! These range
from a bug in the reachable-closure code to a memory error causing
the binary search into the list of object ids to fail. In either
case, we should fail fast and avoid writing the commit-graph file
with bad data.
> commit-graph: writing missing parents is a BUG

- Documentation/git-multi-pack-index.txt
- builtin/multi-pack-index.c
- builtin/repack.c
- midx.c
- midx.h
- packfile.c
- packfile.h
- t/t5319-multi-pack-index.sh
The multi-pack-index provides a fast way to find an object among a large list of pack-files. It stores a single pack-reference for each object id, so duplicate objects are ignored. Among a list of pack-files storing the same object, the most-recently modified one is used.
Create new subcommands for the multi-pack-index builtin.
* 'git multi-pack-index expire': If we have a pack-file indexed by the multi-pack-index, but all objects in that pack are duplicated in more-recently modified packs, then delete that pack (and any others like it). Delete the reference to that pack in the multi-pack-index.
* 'git multi-pack-index repack --batch-size=<size>': Starting from the oldest pack-files covered by the multi-pack-index, find those whose on-disk size is below the batch size until we have a …
> Create 'expire' and 'repack' subcommands for multi-pack-index

- midx.c
- t/t5319-multi-pack-index.sh
This replaces #106. That PR was complicated and difficult to understand because we didn't use structured data, but instead relied on our simple arrays and overloaded that data.
This is a bigger change, but results in code that is (hopefully) easier to understand. The new flow for writing a multi-pack-index is as follows:
1. Construct a list of `midx_info` structs that contain the details of the packs. This list starts with the packs in the existing midx, followed by the new packs to add.  Keep track of the `orig_pack_int_id` for these packs.
2. Construct the list of object entries. The `pack_int_id` we use here corresponds to the `orig_pack_int_id` for the pack we are using.
3. Sort the packs by name.
4. If we have packs to drop, identify where they are in the list of packs. We can use …
> midx: use more structured data for expire

- wt-status-serialize.c
- wt-status.c
Add trace2 regions around serialize and printing.
Add trace2 data messages giving the number of items changed/untracked/ignored.
> Trace2 Part 4: add additional trace regions/data to status

- trace2/tr2_dst.c
Remove warning message when the trace2 destination file could not be opened.
> trace2: fixup: remove warning message when opening trace file

- compat/win32/trace2_win32_process_info.c
Guard against infinite loop while computing the parent process hierarchy.
CreateToolhelp32Snapshot() is used to get a list of all processes on the
system.  Each process entry contains the process PID and PPID (alive at the
time of the snapshot).  We compute the set of ancestors of the current process
by repeated searches on this list.
Testing revealed that the snapshot can contain PPID cycles.  This causes an
infinite loop during the set construction and causes the git.exe command to
hang.
Testing found an instance where 3 processes were in a PPID cycle.  The
snapshot implied that each of these processes was its own great-grandparent.
This should not be possible unless a PID was recycled and just happened to
match up.
For full disclosure, the Windows "System Idle Process" has PID and PPID …
> fixup! trace2: collect Windows-specific process information

- cache.h
- git.c
- pager.c
A bit of housekeeping to reduce the number of patches in our fork.  This reverts commit 3f588065b0 as it no longer fixes the underlying issue so there is no reason to keep hauling it along with every release.
Signed-off-by: Ben Peart <benpeart@microsoft.com>
> fixup! pager: fix order of atexit() calls

- midx.c
Fix "git multi-pack-index verify" to handle repos with thousands
of packfiles.
Midx verify adds the individual "packed_git" structures to the
multi_pack_index.packs array, but it does not add them to the
"repository.objects.packed_git" list.  During the verification
code, each packfile is opened and scanned.  And "pack_open_fds"
is incremented.  If "pack_open_fds" equals the "pack_max_fds"
open_packed_git_1() calls close_one_pack() to LRU-style close
an already open packfile.  But because the packfiles were never
added to the "packed_git" list, close_one_pack() does nothing.
If there are very many packfiles, Git runs out of file descriptors
and fails.
Note that this was observed on Windows when build with GCC and
in a repository with more than (2048-25) packfiles.
Signed-off-by: Jeff …
> midx: verify: add midx packfiles to the packed_git list

- builtin/multi-pack-index.c
- midx.c
- packfile.c
- packfile.h
Sort the set of objects by packfile so that only one packfile needs
to be open at a time.
This is a performance improvement.  Previously, objects were
verified in OID order.  This essentially requires all packfiles
to be open at the same time.  If the number of packfiles exceeds
the open file limit, packfiles would be closed and re-opened
many times.
Signed-off-by: Jeff Hostetler <jeffhost@microsoft.com>
> midx: verify: group objects by packfile to speed up object verification

- convert.c
- t/t0021-conversion.sh
Ensure writing out files properly blocks expanding $Id: when the ident attribute is set for a path under GVFS.
Signed-off-by: Ben Peart <benpeart@microsoft.com>
> fixup! gvfs: ensure all filters and EOL conversions are blocked

- azure-pipelines.yml
- builtin/fetch.c
- compat/mingw.c
- compat/obstack.c
- compat/obstack.h
- compat/poll/poll.c
- compat/win32/exit-process.h
- config.mak.uname
- fetch-pack.c
- kwset.c
- pkt-line.c
- t/t6500-gc.sh
- t/t9822-git-p4-path-encoding.sh
- t/t9833-errors.sh
This backports:
* Two fixes needed to build on the macOS agents of Azure Pipelines, as they are upgraded to macOS Mojave now.
* A fix to allow building on Windows in the presence of v3.x of the MSYS2 runtime.
* A fix (two commits) to fix the flakiness of `t5570-git-daemon.sh` on macOS.
* Speedups to the Azure Pipeline (runs the tests in parallel now).
> Fix the Azure Pipeline (e.g. macOS builds after the upgrade to Mojave)

- wt-status.c
> Address forgotten "DROPME"

- diff.c
Due to some mishandling of the return value of `getenv("GIT_EXTERNAL_DIFF")`, when calling `git difftool` in a worktree with _lots_ of files, Git launched commands with a corrupt command-line.
This was fixed in Git v2.21.0, and here is a backport to vfs-2.20.1.
> Fix problems with `git difftool` and a large number of files

- t/t7524-serialized-status.sh
- wt-status-deserialize.c
With the "--untracked-files=complete" option status computes a
superset of the untracked files.  We use this when writing the
status cache.  If subsequent deserialize commands ask for either
the complete set or one of the "no", "normal", or "all" subsets,
it can still use the cache file because of filtering in the
deserialize parser.
When running status with the "-uno" option, the long format
status would print a "(use -u to show untracked files)" hint.
When deserializing with the "-uno" option and using a cache computed
with "-ucomplete", the "nothing to commit, working tree clean" message
would be printed instead of the hint.
It was easy to miss because the correct hint message was printed
if the cache was rejected for any reason (and status did the full
fallback).
The "struct wt_status …
> status: deserialize with -uno does not print correct hint

- Documentation/git-commit-graph.txt
- Documentation/technical/commit-graph-format.txt
- Documentation/technical/commit-graph.txt
- builtin/commit-graph.c
- builtin/commit.c
- builtin/gc.c
- commit-graph.c
- commit-graph.h
- commit.c
- packfile.h
- t/t5318-commit-graph.sh
- t/t5324-split-commit-graph.sh
This PR matches the commits that Junio is tracking from [this patch series](https://public-inbox.org/git/pull.184.v6.git.gitgitgadget@gmail.com/).
The only commit required that is extra is a merge between `vfs-2.22.0`
and `ds/commit-graph-incremental` because we took `ds/close-object-store`
a bit earlier (we needed it). Also, there was a small conflict in `packfile.[c|h]`
related to `ds/multi-pack-index-expire`.
Here is a copy of the cover letter for that series:
The commit-graph is a valuable performance feature for repos with large
commit histories, but suffers from the same problem as git repack: it
rewrites the entire file every time. This can be slow when there are
millions of commits, especially after we stopped reading from the
commit-graph file during a write in 43d3561 …
> Incremental commit-graph files

- read-cache.c
This series adds per-thread tracing to the do_read_index() and adds regions around the cache-tree extension.  The intent is to show / confirm that index read time is now bounded by the cache-tree
extension (now that we have Ben's multi-threading changes (both the N-1 cache-entry and
the single extension worker threads)).
> Trace2:Gvfs:Experiment: read-cache: trace threading and cache-tree extension

- builtin/reset.c
- cache-tree.c
Add a region around prime_cache_tree().
This is an experiment to measure time spent in prime_cache_tree()
which seems to be a major factor during "git reset --hard" on the OS
repo.
This series can probably be dropped at a future point.
> trace2:gvfs:experiment: add region for prime_cache_tree()

- config.c
This is a companion PR to git-for-windows/git#2258
It is necessary because MSYS2 (and therefore, Git for Windows' SDK) switched to GCC v9.x for the MINGW builds.
> Support building with GCC v9.x

- builtin/checkout.c
- remote.c
- trace2/tr2_tgt_event.c
- unpack-trees.c
This patch series updates the existing "exp" style tracing intended for `checkout` and `reset`
to have named categories.  It adds ahead/behind information.  And it adds data for the number
of files created or deleted during a checkout.
I've temporarily increased the default event-depth because some of the unpack_trees()
events are more deeply nested.
> trace2:gvfs:experiment Add addition unpack_trees() and report_tracking() data

- commit-graph.c
- t/t5324-split-commit-graph.sh
The commit message below describes the bug. This has been sent upstream
hopefully in time for v2.23.0. If we are taking 2.23.0 soon, then we would not
need this fix.
The question for @jrbriggs and others is: do we rush this fix to the version
of microsoft/vfsforgit in EA? There are possible reasons that this is an
edge-case enough to ignore:
1. It only affects the split commit-graph when a non-base file has an
octopus merge commit. Only one octopus merge exists in the OS repo
right now.
2. It will not _break_ users, but will cause "warning: commit-graph chain
does not match" warnings and cause increasing performance issues as
the base commit-graph files far further and further behind.
I'm open to all options here.
Thanks,
-Stolee
---
In 1771be90 "commit-graph: merge commit-graph chains" …
> [BUGFIX] commit-graph: fix bug around octopus merges

- commit-graph.c
- commit-graph.h
- commit.h
- t/t5318-commit-graph.sh
The parse_commit_no_graph() method was added in 43d35618 ("commit-graph
write: don't die if the existing graph is corrupt" 2019-03-25) as a way
to avoid persisting bad data across commit-graph files. That is, if the
commit-graph file has undetected corrupt data -- such as a flipped bit
in a parent int-id value -- then that data will persist to the next
commit-graph file. The parse_commit_no_graph() method was used to always
use the pack data directly instead.
Unfortunately, this comes at a significant performance cost. In both
time and memory, parsing from pack files is much slower than parsing
from the commit-graph file. In a repository with 4.5 million commits,
this can lead to Git taking up to 11gb of memory to rewrite the file.
Now that the incremental commit-graph file format exists, …
> commit: remove parse_commit_no_graph()

- .gitignore
- Documentation/config/core.txt
- Documentation/git-clone.txt
- Documentation/git-read-tree.txt
- Documentation/git-sparse-checkout.txt
- Makefile
- builtin.h
- builtin/clone.c
- builtin/reset.c
- builtin/sparse-checkout.c
- cache.h
- config.c
- dir.c
- dir.h
- environment.c
- git.c
- t/t1091-sparse-checkout-builtin.sh
- unpack-trees.c
I'm creating this PR for a fourth time (see #163, #171, and #178 for earlier versions). This version is tracking my progress to create something that can be sent as an RFC upstream, but _also_ can be used to start the sparse feature branch. This is based on v2.23.0.
Note: I currently have conflicts with the virtual filesystem feature, and I'll resolve those with a merge commit when I'm ready. I'm just creating this for tracking progress at the moment, but can also be a place for early feedback.
TODOs:
This includes performance improvements with the hashset-based matching algorithm, but I'll leave further enhancements as smaller steps on top. Here are a few things I want to try:
1. Track the maximum depth of a prefix pattern, so we know to not run hashes for deeper paths.
2. Use the "known …
> Sparse-checkout builtin: upstreamable version

- builtin/checkout.c
In #183, I reverted a change to builtin/checkout.c that slowed
down 'git checkout -b'. That change introduced a new instance of
the core_apply_sparse_checkout global value that was not in the
previous version. I then merged #180 without regenerating a
build. My bad.
This fixes that remaining core_apply_sparse_checkout instance.
> checkout: fix leftover global constant

- Documentation/git-multi-pack-index.txt
- builtin/multi-pack-index.c
- midx.c
- midx.h
- t/t5319-multi-pack-index.sh
These changes are a port of https://github.com/gitgitgadget/git/pull/315 to the `multi-pack-index` command.
> multi-pack-index: add --no-progress to verify

- builtin/sparse-checkout.c
- dir.c
- dir.h
- t/t1091-sparse-checkout-builtin.sh
If a user provides folders A/ and A/B/ for inclusion in a cone-mode
sparse-checkout file, the parsing logic will notice that A/ appears
both as a "parent" type pattern and as a "recursive" type pattern.
This is unexpected and hence will complain via a warning and revert
to the old logic for checking sparse-checkout patterns.
Prevent this from happening accidentally by sanitizing the folders
for this type of inclusion in the 'git sparse-checkout' builtin.
This happens in two ways:
1. Do not include any parent patterns that also appear as recursive
patterns.
2. Do not include any recursive patterns deeper than other recursive
patterns.
**Note:** The old behavior surfaces as a performance issue, not a
correctness issue. The test checks the expected data in the
sparse-checkout file to ensure …
> sparse-checkout: sanitize for nested folders

- fsmonitor.c
- t/t7519-status-fsmonitor.sh
- t/t7519/fsmonitor-env
`fill_fsmonitor_bitmap` was populating `fsmonitor_dirty` with all entries in the cache, even those that have been marked for removal.  This caused a problem when subsequent git commands read the index, as the bit's position in `fsmonitor_dirty` would no longer match the index in the cache.  Additionally, the number of entries in `fsmonitor_dirty` could exceed the number of entries in the cache.  If the number of entries in `fsmonitor_dirty` exceeded the number of entries in the cache it resulted in a segfault when `tweak_fsmonitor` was called because
`ewah_each_bit` would go beyond the bounds of the cache.
> fsmonitor: don't fill bitmap with removed entries

- gvfs-helper.c
When two gvfs-helper processes are the first to create a loose object
directory, the processes (A and B in the timeline below) could have
the following race:
1. A sees that the directory does not exist.
2. B sees that the directory does not exist.
3. A creates the directory with success.
4. B fails to create the directory and fails.
Instead of having B fail here, just check for the directory's
existence before reporting an error. That solves the race and
allows tests to pass.
> gvfs-helper: fix race condition when creating loose object dirs
